{
    "data": {
        "arUpiInputUtrSwitch": true,
        "isShowAppDownloadUp": false,
        "isShowAppDownloadDown": true,
        "isShowRewardCenter": true,
        "isShowLotteryDragon": true,
        "isSplitLocalEWallet": true,
        "jackportMaxReswadAmount": 500.00,
        "projectName": "in999",
        "projectLogo": "https://ossimg.in999-in.com/in999/other/h5setting_20240614134808nnhk.png",
        "languages": "en|hd|ta|te",
        "webIco": "https://ossimg.in999-in.com/in999/other/h5setting_202406141348201846.png",
        "headLogo": "https://ossimg.in999-in.com/in999/other/h5setting_20240614134813hi2h.png",
        "dollarSign": "₹",
        "upperOrLower": "0",
        "defaultCurrentLanguage": "en",
        "registerMobile": "1",
        "registerEmail": "0",
        "areaPhoneLenList": [
            {
                "area": "+91",
                "len": "10"
            }
        ],
        "registerSms": "0",
        "isOpenLoginChangeLanguage": "1",
        "rewardValidityTime": 1,
        "electronicWinRateExternalLink": "",
        "electronicWinRateImgUrl": "",
        "isShowElectronicWinRateExternalLink": false,
        "isShowAppHandCodeWashingSwitch": true,
        "isShowHotGameWinOdds": true,
        "ossUrl": "https://ossimg.in999-in.com",
        "bigTurntableLink": "",
        "bigTurntableImgUrl": "",
        "telegramExternalLink": "",
        "telegramImgUrl": "",
        "isOpenActivityAward": true,
        "isOpenTurntable": false,
        "isPartnerReward": true,
        "isSelfCustomerService": true,
        "webSiteUrl": "https://www.dv48cn.com",
        "isOpenFacebookEvent": false,
        "firstDepositRewardCodeAmount": "1",
        "isOpenRegisterPhoneFirstZeroSwitch": false,
        "eventRegionConfigList": null,
        "isOpenAdjustEvent": false,
        "firebaseConfig": {
            "apiKey": null,
            "authDomain": null,
            "projectId": null,
            "storageBucket": null,
            "messagingSenderId": null,
            "appId": null,
            "measurementId": null,
            "keyPair": null
        },
        "isOpenArLottery": false,
        "isSwitchSaasBalance": false,
        "isOpenInvitedWheel": true,
        "invitedWheelTotalPrizeAmount": 500.0,
        "invitedWheelImgUrl": "https://ossimg.in999-in.com/in999/tab/wheel.png",
        "isOpenDownAppRewardSwitch": false,
        "isShowDownAppBonusAmountSwitch": false,
        "downAppBonusAmount": 0.0,
        "needKycValidIsOpen": true,
        "needFastKycValidIsOpen": true,
        "lotteryDragonIcon": null,
        "bonusCenterImgUrl": "",
        "isShowBonusCenterExternalLink": true,
        "isOpenBrowserConsoleDebug": true
    },
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serviceNowTime": "2025-12-14 18:34:36"
}